name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          # - 'head'
        gemfile:
          - gemfiles/rails_6_0.gemfile
          - gemfiles/rails_6_1.gemfile
          - gemfiles/rails_7_0.gemfile
          # - gemfile: gemfiles/rails_head.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run test
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: bundle exec rake test
